apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vm
  namespace: openshift-gitops
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: "{{ nameNormalized }}-vm"
    spec:
      project: default
      source:
        repoURL: https://github.com/0xFelix/cloudland2025-demo.git
        targetRevision: HEAD
        path: vm/helm
      destination:
        server: "{{ server }}"
        namespace: cloudland2025-demo
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
