apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sysinfo
spec:
  tls:
  - {}
  rules:
  - host: sysinfo.{{ .Values.baseDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sysinfo
            port:
              number: 8080
