apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
  name: fedora-custom-image-cron
spec:
  garbageCollect: Outdated
  managedDataSource: fedora-custom
  schedule: 31 0/12 * * *
  template:
    metadata: {}
    spec:
      source:
        registry:
          pullMethod: node
          url: docker://quay.io/containerdisks/fedora:latest
      storage:
        resources:
          requests:
            storage: 30Gi
