apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
  name: fedora-custom-image
spec:
  source:
    registry:
      url: docker://quay.io/containerdisks/fedora:latest
  storage:
    resources:
      requests:
        storage: 30Gi
